week 3 assessment update
learn-academy-2022-echo/week-3-assessment-ResetReesi pull request #1
Opened 2022-08-22 21:45 UTC by ResetReesi

# Submitting Week 3 Assessment

### ✅ Completed Files
Mark the following as confirmation that the files in this repository are complete.
- [ ✅] Coding Challenges
- [ ✅] Interview Questions
- [✅ ] React Debugging

### 📝 Feedback
If you would like specific feedback on a particular problem please leave details here:

2022-08-23 16:52 UTC, WalkerTexas-coder requested changes
Okay Brook, there some work to do! I found where you copied your interview answers from. I am putting in a request for changes that you redo all of your interview answers and researched answers. They must be in your own words entirely and not copied at all. As per the requirements of this assessment. Once those changes are made alert me and I will re reviews this assessment. Also check out the feedback I gave you in the coding section.

2022-08-23 16:52 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +    }
This is a great attempt and honestly it has all the ingredients for the recipe here! But putting the ingredients together correctly is also half the journey. 

Go and lookup function syntax in javascript unit 1 and check out what's going on with the curly brackets or "code block"

2022-08-23 16:52 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +const sorted= odds.sort
A proper function should only be declared once and reused for each variable. Again check out whats going on with functions in javascript unit 1!

2022-08-23 16:52 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +};
This is amazing code! I would love to see the pseudo code that explains this!

2022-08-23 16:52 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +// Output: pushing numbers to a  array with the accumulation sum of the original array
Okay but this pseudo code doesn't express **"how"** to solve this problem-- just what the problem is.

2022-08-23 16:52 UTC, WalkerTexas-coder commented on interview-questions.md
> +const App = <h1>Welcome to GeeksforGeeks</h1>;
So please remember, even stitching together answers from multiple sites is still plagiarizing. 

[JSX (JavaScript + XML) is an extension of JavaScript that permits you to write down HTML directly within JavaScript, which features a few benefits of creating your code more readable and exercising the complete power of JavaScript within HTML.](https://www.geeksforgeeks.org/what-are-the-differences-between-jsx-and-html/#:~:text=Introduction%20to%20JSX%3A%20JSX%20(JavaScript,power%20of%20JavaScript%20within%20HTML. )

[What is JSX Exactly?
JSX stands for JavaScript XML. It is a syntax extension for JavaScript that lets you use HTML tags right inside your JavaScript file. ](https://www.webtips.dev/javascript-vs-jsx/)


[ h1 Welcome to GeeksforGeeks /h1 ;](https://www.geeksforgeeks.org/reactjs-functional-components/)

2022-08-24 23:32 UTC, ResetReesi commented
I will take everything I learned this week and  apply it to next week , so I can become a better developer.

2022-08-24 23:32 UTC, merged